language: node_js
node_js:
      - "10.16.3"
      - "9"
      - "8"
install:
      - npm i 
before_script:
      - node compile.js
script:
      - ganache-cli -p 7545 > /dev/null &
      - npm test 
